import { type MuseumDocument, type Room, type Asset, type Region } from './model';
const room = (
  id: string,
  name: string,
  x: number,
  z: number,
  floor = 0,
  kind: Room['kind'] = 'gallery',
): Room => ({
  id,
  name,
  x,
  z,
  floor,
  kind,
  rotation: 0,
  color: '#eeece5',
  finish: 'wood',
  pages: [
    '# A slower way of seeing\n\nWelcome to Still / Life, a collection about the quiet places we pass every day.\n\nTake your time. There is no right route through the museum.',
    '## Make yourself at home\n\nUse the arrows to explore, or switch to walking mode. Select an artwork to read its story.\n\nTurn on the audioguide to listen as you wander.',
  ],
  shelves: ['art-1', 'art-3', 'art-5'],
});
export const sample: MuseumDocument = {
  schemaVersion: 1,
  name: 'Still / Life',
  subtitle: 'An exploration of light, landscape, and the spaces in between.',
  language: 'en',
  audioguide: true,
  defaultFrame: { preset: 'wood', width: 0.055, mat: 0.07 },
  entrance: 'welcome',
  rooms: [
    room('welcome', 'The welcome room', 0, 0, 0, 'information'),
    room('light', 'Studies in light', 0, -1),
    room('land', 'The open landscape', 1, -1),
    room('shop', 'The museum shop', 2, -1, 0, 'shop'),
    room('upper', 'A different perspective', 2, -1, 1),
    room('upper-west', 'Quiet geometries', 1, -1, 1),
    room('stair-top', 'The upper landing', 1, 0, 1),
    room('reading', 'The reading room', -2, 0),
  ],
  connections: [
    { id: 'c1', a: 'welcome', b: 'light', kind: 'door', route: [] },
    { id: 'c2', a: 'light', b: 'land', kind: 'merged', route: [] },
    { id: 'c3', a: 'land', b: 'shop', kind: 'door', route: [] },
    { id: 'c4', a: 'shop', b: 'upper', kind: 'spiral', route: [] },
    { id: 'c5', a: 'upper', b: 'upper-west', kind: 'door', route: [] },
    { id: 'c6', a: 'upper-west', b: 'stair-top', kind: 'door', route: [] },
    { id: 'c7', a: 'welcome', b: 'stair-top', kind: 'stairs', route: [] },
    { id: 'c8', a: 'welcome', b: 'reading', kind: 'corridor', route: [] },
  ],
  assets: [
    [
      'After the rain',
      'A landscape reduced to its essential shapes. Pale hills fold into one another, while the afternoon light settles on the water.',
      'landscape',
      1400,
      1000,
    ],
    [
      'An ordinary afternoon',
      'Warm light moves across an empty room. The simplest forms become a record of passing time.',
      'arch',
      900,
      1200,
    ],
    [
      'Where the water rests',
      'At the meeting of land and sea, the horizon becomes a quiet line between two shades of blue.',
      'sea',
      1400,
      900,
    ],
    [
      'A small arrangement',
      'Three familiar objects, held for a moment in the soft geometry of daylight.',
      'still',
      1000,
      1200,
    ],
    [
      'The long way home',
      'The path winds through a landscape remembered rather than observed. Some places stay with us long after we leave.',
      'hills',
      1400,
      1000,
    ],
    [
      'Intervals',
      'A study in balance, color, and the space between things.',
      'abstract',
      1000,
      1300,
    ],
  ].map(
    ([title, explanation, file, width, height], i) =>
      ({
        id: `art-${i + 1}`,
        title,
        explanation,
        attribution: 'E-xhibit studio · 2026 · Original vector study',
        width,
        height,
        bytes: 0,
        mime: 'image/png',
        source: `/art/${file}.svg`,
        variants: {
          '512': `/art/${file}.svg`,
          '1024': `/art/${file}.svg`,
          '2048': `/art/${file}.svg`,
        },
        downloadable: false,
        ready: true,
      }) as Asset,
  ),
  regions: [
    ['light:north', 'art-1', 0.25, 2.6],
    ['light:north', 'art-2', 3.15, 2.6],
    ['land:north', 'art-3', 0.25, 5.5],
    ['land:south', 'art-4', 0.25, 2.6],
    ['land:south', 'art-5', 3.15, 2.6],
    ['reading:west', 'art-6', 0.25, 5.5],
    ['upper:north', 'art-5', 0.25, 5.5],
    ['upper-west:north', 'art-6', 0.25, 5.5],
  ].map(
    ([wall, assetId, x, w], i) =>
      ({ id: `exhibit-${i}`, wall, assetId, x, w, y: 0.45, h: 2.9, plaque: 'below' }) as Region,
  ),
  unplaced: [],
};
